<a href="https://colab.research.google.com/github/franciscosalido/tensorflow/blob/master/Construindo_uma_Rede_Neural__Artificial_no_Tensorflow_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Etapa 1: Instalando o Tensorflow 2.0**

In [1]:
 %tensorflow_version 2.x

TensorFlow 2.x selected.


# **Etapa 2: Importando as bilbiotecas e base de dados**

In [0]:
import tensorflow as tf
import numpy as np
import datetime

from tensorflow.keras.datasets import fashion_mnist

In [4]:
tf.__version__

'2.1.0'

# **Etapa3: Pré-processamento**

## Carregando a base de dados

In [8]:
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [9]:
X_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [10]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

In [11]:
y_train

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [12]:
y_train[0]

9

## Normalizando as imagens
DIvidimos cada pixel das imagnes das bases de treinamento e teste, utilizando o maior valor que é 255, com isso, cada pixel estará na faixa entre 0 a 1, desta forma a rede neural vai treinar muito mais rápida.

In [0]:
X_train = X_train / 255.0

In [0]:
X_test = X_test / 255.0

In [0]:
X_train[0]

## Remodelando (reshaping) a base de dados

In [13]:
X_train.shape

(60000, 28, 28)

In [0]:
# Como a dimensão de cada imagem é 28x28, mudamos toda a base de dados para o formato (-1 (todos elementos), altura * largura)
X_train = X_train.reshape(-1, 28*28)

In [16]:
X_train.shape

(60000, 784)

In [0]:
X_test = X_test.reshape(-1, 28*28)

In [18]:
X_test.shape

(10000, 784)

In [19]:
X_test[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

# **Etapa 4: Construindo a Rede Neural Artificial**

## Definindo o modelo

##### Definimos um objeto do tipo Sequencial (sequência de camadas)

In [0]:
model = tf.keras.models.Sequential()

In [21]:
model

## Adicionando a primeira camada densa (fully-connected)

##### Hyper-parâmetros de camada
*   número de units/neurônios: 128
*   função de ativação ReLu
*   INPUT_SHAPE (camada de entrada): (784,)





In [0]:
model.add(tf.keras.layers.Dense(units=128, activation="relu", input_shape=(784, )))

##### Adicionando o Dropout
Dropout é uma técnica de regularizac'ão na qual alguns neurônios da camada tem seu valor mudado para zero, ou seja, durante o treinamento sesse neurônios não serão atualizados. Com isso temos menos chances de ocorrer overfitting

In [0]:
model.add(tf.keras.layers.Dropout(0.2))

##### Adicionando a camada de saída


*   Units: neurônios de classes (10 na base de dados Fashion MNIST)
*   Função de ativação: softmax



In [0]:
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

## Compilando o Modelo


*   Optimizer (otimizador): Adam
*   Loss (função de erro): Sparse sotmax (categorical) crossentropy



In [0]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_crossentropy'])

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


## Treinando o Modelo

In [29]:
model.fit(X_train, y_train, epochs=10)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 5s 82us/sample - loss: 0.8025 - sparse_categorical_crossentropy: 0.8025
Epoch 2/10
60000/60000 [==============================] - 5s 83us/sample - loss: 0.7934 - sparse_categorical_crossentropy: 0.7934
Epoch 3/10
60000/60000 [==============================] - 5s 80us/sample - loss: 0.7826 - sparse_categorical_crossentropy: 0.7826
Epoch 4/10
60000/60000 [==============================] - 5s 83us/sample - loss: 0.7777 - sparse_categorical_crossentropy: 0.7777
Epoch 5/10
60000/60000 [==============================] - 5s 83us/sample - loss: 0.7773 - sparse_categorical_crossentropy: 0.7773
Epoch 6/10
60000/60000 [==============================] - 5s 80us/sample - loss: 0.7700 - sparse_categorical_crossentropy: 0.7700
Epoch 7/10
60000/60000 [==============================] - 5s 80us/sample - loss: 0.7620 - sparse_categorical_crossentropy: 0.7620
Epoch 8/10
60000/60000 [==============================] - 5s 79us/s

## Avaliaçào do modelo e previsão

In [30]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

10000/10000 [==============================] - 0s 48us/sample - loss: 0.6616 - sparse_categorical_crossentropy: 0.6616


In [31]:
print('Test accuracy: {}'.format(test_accuracy))

Test accuracy: 0.6616101861000061


In [32]:
test_loss

0.6616100288391114