<a href="https://colab.research.google.com/github/franciscosalido/tensorflow/blob/master/Introdu%C3%A7%C3%A3o_TensorFlow_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow 1.0

## How run Tensorflow 1.x in Google Colab `%tensorflow_version 1.x or 2.x` BEFORE the import tensorflow as tf

In [0]:
# Restart runtime using 'Runtime' -> 'Restart runtime...'
%tensorflow_version 1.x

In [0]:
import tensorflow as tf

In [0]:
print(tf.__version__)

1.15.0


## Constante

In [0]:
 # Define a constant in the Tensorflow.
 tensor = tf.constant([[23, 4], [32, 51]])

In [0]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [0]:
# Inicialize a Tensorflow Session
tensor.eval()

ValueError: ignored

##### Acessando o Valor de uma Constante

In [0]:
session = tf.Session()

In [0]:
session.run(tf.global_variables_initializer())

In [0]:
tensor_value = session.run(tensor)

In [0]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

## Variáveis

In [0]:
# Define a variable in Tensorflow
variable = tf.Variable(([30, 20], [10, 45]))

In [0]:
variable

<tf.Variable 'Variable_1:0' shape=(2, 2) dtype=int32_ref>

In [0]:
# Se uma sessão não for iniciada, não podemos acessar os valores das variáveis
variable.eval()

ValueError: ignored

##### Acessando os valores de uma variável

In [0]:
# Iniciando uma sessão
session = tf.Session()

In [0]:
# Iniciando TODAS as variáveis de uma sessão
session.run(tf.global_variables_initializer())

In [0]:
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

# Tensorflow 2.0

## Importanto e definido a biblioteca do Tensorflow 2.0

In [0]:
# Restart runtime using 'Runtime' -> 'Restart runtime...'
%tensorflow_version 2.x

TensorFlow 2.x selected.


In [0]:
import tensorflow as tf
import numpy as np


In [0]:
print(tf.__version__)

2.1.0


## Constantes

##### Definindo uma constante

In [0]:
# Definindo uma constante no Tensorflow 2.0
tensor_20 = tf.constant(([23, 4], [32, 51]))

In [0]:
# Acessando a variável
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [0]:
#Acessando as dimensões da variável
tensor_20.shape

TensorShape([2, 2])

##### Acessando os valores de uma constante

In [0]:
# Acessando os valores de um tensor com o numpy e sem precisar de uma sessão
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
# Podemos converter um array do numpy em um tensor do Tensorflow 2.0
numpy_tensor = np.array(([23, 4], [32, 51]))

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [0]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

## Variáveis

##### Definindo uma variável

In [0]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

##### Acessando os valores de uma variável

In [0]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

##### Alterando um valor específico de uma variável

In [0]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [0]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

## Operações com tensores

In [0]:
tensor = tf.constant([[1, 2], [3, 4]])

In [0]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

##### Adição entre um escalar e um tensor

In [0]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

##### Multiplicação entre um escalar e um tensor

In [0]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

##### Usando funções NUmpy nos tensores do TensorFlow

In [0]:
# Obtendo o quadrado de todos os membros de um tensor
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [0]:
# Obtendo a raiz quadrada de todos os membros de um tensor
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

##### Dot Product (produto escalar) entre dois tensores

In [0]:
np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

## **Strings no Tensorflow 2.0**

In [0]:
tf_string = tf.constant('Tensorflow')
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'Tensorflow'>

##### Operações simples com strings

In [0]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [0]:
tf.strings.unicode_decode(tf_string, 'UTF8')

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

##### Armazenando arrays (vetores) de strings

In [0]:
tf_string_array = tf.constant(['Tensorflow', 'Deep Learnig', 'AI'])

In [0]:
# Interagindo através do array de TF string
for string in tf_string_array:
  print(string)

tf.Tensor(b'Tensorflow', shape=(), dtype=string)
tf.Tensor(b'Deep Learnig', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
